mode: train
loss_function:
  name: focal_loss
  gamma: 0.0
  alpha:
    - 0.0
    - 0.0
num_workers: 3
batch_size: 32
epochs: 50
optimizer:
  name: Adam
  lr: 0.001
  scheduler: None
  weight_decay: 0.0001
accuracy:
  beta: 1

